const create = type => payload => ({ type, payload });
const createEmpty = type => () => ({ type });

export const actionTypes = {
	AUTH: 'user/auth',
	AUTH_SUCCESS: 'user/auth/success',
	AUTH_FAIL: 'user/auth/fail',
	LOGIN: 'user/login',
	LOGIN_FAIL: 'user/login/fail',
	LOGIN_MODAL_TOGGLE: 'user/login_modal/toggle',
	LOGIN_NO_OAUTH_ACCOUNTS: 'user/login/no_oauth',
	SIGNUP_TOKEN_RECEIVED: 'user/signup_token/received',
	USERNAME_INPUT_CHANGE: 'user/username/input',
	USERNAME_INPUT_FEEDBACK: 'user/username/feedback',
	USERNAME_INPUT_SUBMIT: 'user/username/submit',
	CHANNEL_MODAL_TOGGLE: 'user/channel_modal/toggle',
	CHANNEL_INPUT_CHANGE: 'user/channel_name/input',
	CHANNEL_INPUT_FEEDBACK: 'user/channel_name/feedback',
	CHANNEL_INPUT_SUBMIT: 'user/channel_name/submit',
	CREATE_CHANNEL_SUCCESS: 'user/channel_name/success',
	USER_AVATAR_UPLOAD: 'user/avatar/upload',
	USER_COVER_UPLOAD: 'user/cover/upload',
	CHANNEL_AVATAR_UPLOAD: 'user/channel/avatar/upload',
	CHANNEL_COVER_UPLOAD: 'user/channel/cover/upload',
	CHANNEL_DELETE: 'user/channel/delete',
	CHANNEL_DELETE_FAILED: 'user/channel/delete/failed',
	IMG_UPLOAD_SUCCESS: 'user/img_upload/success',
	IMG_UPLOAD_FAIL: 'user/img_upload/fail',
	USER_ABOUT_SAVE: 'user/about/save',
	CHANNEL_ABOUT_SAVE: 'user/channel/about/save',
	ABOUT_SAVE_FAILED: 'user/about/failed',
};

export default {
	auth: create(actionTypes.AUTH),
	authSuccess: create(actionTypes.AUTH_SUCCESS),
	authFail: create(actionTypes.AUTH_FAIL),
	login: create(actionTypes.LOGIN),
	toggleLoginModal: create(actionTypes.LOGIN_MODAL_TOGGLE),
	noOauthAccounts: create(actionTypes.LOGIN_NO_OAUTH_ACCOUNTS),
	receivedSignupToken: create(actionTypes.SIGNUP_TOKEN_RECEIVED),
	usernameInputChange: create(actionTypes.USERNAME_INPUT_CHANGE),
	usernameInputFeedback: create(actionTypes.USERNAME_INPUT_FEEDBACK),
	usernameInputSubmit: createEmpty(actionTypes.USERNAME_INPUT_SUBMIT),
	toggleChannelModal: create(actionTypes.CHANNEL_MODAL_TOGGLE),
	channelInputChange: create(actionTypes.CHANNEL_INPUT_CHANGE),
	channelInputFeedback: create(actionTypes.CHANNEL_INPUT_FEEDBACK),
	channelInputSubmit: create(actionTypes.CHANNEL_INPUT_SUBMIT),
	createChannelSuccess: create(actionTypes.CREATE_CHANNEL_SUCCESS),
	uploadUserAvatar: create(actionTypes.USER_AVATAR_UPLOAD),
	uploadUserCover: create(actionTypes.USER_COVER_UPLOAD),
	uploadChannelAvatar: create(actionTypes.CHANNEL_AVATAR_UPLOAD),
	uploadChannelCover: create(actionTypes.CHANNEL_COVER_UPLOAD),
	deleteChannel: create(actionTypes.CHANNEL_DELETE),
	deleteChannelFailed: createEmpty(actionTypes.CHANNEL_DELETE_FAILED),
	imgUploadSuccess: createEmpty(actionTypes.IMG_UPLOAD_SUCCESS),
	imgUploadFailed: createEmpty(actionTypes.IMG_UPLOAD_FAIL),
	saveUserAbout: create(actionTypes.USER_ABOUT_SAVE),
	saveChannelAbout: create(actionTypes.CHANNEL_ABOUT_SAVE),
};
