env:
  browser: true
  node: true
  es6: true

parserOptions:
  # ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

extends:
  - airbnb-base
  - plugin:react/recommended

plugins:
  - import
  - react


settings:
  # Inspect the webpack config to resolve alias in import statements
  import/resolver: 
    webpack:
      config: './webpack.config.js'

rules:
  indent:
    - error
    - tab
    - FunctionExpression:
        body: 1
        parameters: 2
      FunctionDeclaration:
        body: 1
        paremeters: 2
      CallExpression:
        arguments: 1
      SwitchCase: 1
  no-tabs: off
  no-console: error


  # Rules for the import plugin
  # Don't throw an error when we import dev dependencies
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  # Don't force consistent file extensions. We can use any extension or none at all
  import/extensions: off
  # We can import ComponentName as Redux continer and { ComponentName } as React class
  import/no-named-as-default: off