files:
  include:
    - 'src/**/*.css'
    - 'src/**/*.scss'
  ignore: src/static/styles/global/normalize.css
options:
  formatter: stylish
rules:
  indentation:
    - 1
    - size: tab
  property-sort-order: 0
  class-name-format: 0
  force-element-nesting: 0
  no-color-literals: 0
  no-transition-all: 0
  nesting-depth:
    - 1
    - max-depth: 4
