export const MAX_UNLISTED_BROADCAST_NAME_LEN = 24;

export const icon = {
	color: '#555',
	strokeWidth: 1.3,
	size: 32,
};

export const screenIcon = {
	color: '#555',
	strokeWidth: 4.5,
	size: 44,
};

export const videoLayouts = {
	SOLO: 'solo',
	NEWS: 'news',
	HOST: 'host',
	GROUP: 'group',
	SCREEN: 'screen',
	PRESENTATION: 'presentation',
};

export const userTypes = {
	HOST: 'host',
	VIEWER: 'viewer',
	QUEUE: 'queue',
	GUEST: 'guest',
};

export const videoRoles = {
	MODERATOR: 'moderator',
	STUDENT: 'student',
};

export const appMessageTypes = {
	CHAT: 'chat',
	LAYOUT: 'layout',
	LIVE: 'live',
	DEAD: 'dead',
	PAY: 'pay',
	SETTINGS: 'settings',
};

export const alerts = {
	WEBRTC_NO_IOS: 'webrtcNoIos',
	WEBRTC_UPDATE_IOS: 'webrtcUpdateIos',
	WEBRTC_UNSUPPORTED_BROWSER: 'webrtcUnsupportedBrowser',
	WEBRTC_UPDATE_BROWSER: 'webrtcUpdateBrowser',
	WEBRTC_UNSUPPORTED: 'webrtcUnsupported',
	VIEWER_ROOM_IS_FULL: 'viewerRoomIsFull',
	ROOM_NOT_FOUND: 'roomNotFound',
	SUMMON_ROOM_IS_FULL: 'summonRoomIsFull',
	SUMMON_FAILED: 'summonFailed',
	PUBLISHER_WEBRTC_FAILED: 'publisherWebrtcFailed',
	PUBLISHER_ROOM_IS_FULL: 'publisherRoomIsFull',
	DEVICES_NO_MIC: 'devicesNoMic',
	DEVICES_NO_CAMERA: 'devicesNoCamera',
	DEVICES_NO_AUDIO: 'devicesNoAudio',
	DEVICES_NOT_SENDING_AUDIO: 'devicesNotSendingAudio',
	DEVICES_FACE_TIME_CAMERA_BLOCKED: 'devicesFaceTimeCameraBlocked',
	DEVICES_ACCESS_DENIED: 'devicesAccessDenied',
	DEVICES_NOT_READABLE: 'devicesNotReadable',
	DEVICES_CAPTURE_FAILED: 'devicesCaptureFailed',
	SCREEN_UNSUPPORTED_BROWSER: 'screenUnsupportedBrowser',
	SCREEN_UPDATE_BROWSER: 'screenUpdateBrowser',
	SCREEN_NO_EXTENSION: 'screenNoExtension',
	SCREEN_UNSUPPORTED: 'screenUnsupported',
	SCREEN_ACCESS_DENIED: 'screenAccessDenied',
	SCREEN_CAPTURE_FAILED: 'screenCaptureFailed',
	EXTENSION_DOWNLOAD_SUCCESS: 'extensionDownloadSuccess',
	EXTENSION_DOWNLOAD_FAILED: 'extensionDownloadFailed',
	RESTREAM_FAILED: 'restreamFailed',
	RESTREAM_KEY_FAILED: 'restreamKeyFailed',
	RESTREAM_STOPPED: 'restreamStopped',
	RESTREAM_ENABLE_YOUTUBE: 'restreamEnableYoutube',
	QUEUE_JOIN_FAILED: 'queueJoinFailed',
	CHAT_SUBMIT_FAILED: 'chatSubmitFailed',
};

export const MAX_STREAMS_PER_ROOM = 5;

export const randomBroadcastNames = [
	'apple',
	'arm',
	'bike',
	'bird',
	'book',
	'chin',
	'class',
	'clover',
	'club',
	'corn',
	'crayon',
	'crow',
	'crown',
	'crowd',
	'desk',
	'dirt',
	'dress',
	'fang',
	'field',
	'flag',
	'flower',
	'fog',
	'game',
	'heat',
	'hill',
	'home',
	'juice',
	'kite',
	'lake',
	'mask',
	'mice',
	'mint',
	'meal',
	'moon',
	'morning',
	'name',
	'nest',
	'nose',
	'pear',
	'pen',
	'pencil',
	'plant',
	'rain',
	'river',
	'road',
	'rock',
	'room',
	'rose',
	'seed',
	'shape',
	'shoe',
	'shop',
	'show',
	'sink',
	'snail',
	'snake',
	'snow',
	'soda',
	'sofa',
	'star',
	'step',
	'stew',
	'stove',
	'straw',
	'string',
	'summer',
	'swing',
	'table',
	'tank',
	'team',
	'tent',
	'test',
	'toes',
	'tree',
	'vest',
	'water',
	'wing',
	'winter',
	'bat',
	'bed',
	'bun',
	'can',
	'cake',
	'cap',
	'car',
	'cat',
	'cub',
	'cup',
	'dad',
	'day',
	'dog',
	'dust',
	'fan',
	'feet',
	'gun',
	'hall',
	'hat',
	'hen',
	'jar',
	'kite',
	'map',
	'pan',
	'pet',
	'pie',
	'pot',
	'rat',
	'sun',
	'toe',
	'tub',
	'van',
	'alarm',
	'animal',
	'bait',
	'balloon',
	'bath',
	'bead',
	'beam',
	'bean',
	'boot',
	'bread',
	'brick',
	'camp',
	'chicken',
	'children',
	'crook',
	'deer',
	'dock',
	'doctor',
	'downtown',
	'drum',
	'dust',
	'eye',
	'fight',
	'flesh',
	'food',
	'frog',
	'goose',
	'grade',
	'grape',
	'grass',
	'hook',
	'horse',
	'jail',
	'jam',
	'kitten',
	'light',
	'lock',
	'lunch',
	'meal',
	'notebook',
	'owl',
	'pail',
	'park',
	'plot',
	'rabbit',
	'rake',
	'robin',
	'sail',
	'scale',
	'sea',
	'soap',
	'song',
	'spark',
	'space',
	'spot',
	'spy',
	'summer',
	'tiger',
	'toad',
	'town',
	'trail',
	'tray',
	'trick',
	'trip',
	'vase',
	'winter',
	'water',
	'week',
	'wheel',
	'wish',
	'wool',
	'yard',
	'zebra',
	'actor',
	'airplane',
	'airport',
	'army',
	'baseball',
	'brush',
	'bushes',
	'butter',
	'cast',
	'cave',
	'cent',
	'cherries',
	'cherry',
	'cobweb',
	'coil',
	'dinner',
	'eggnog',
	'elbow',
	'face',
	'fireman',
	'flavor',
	'gate',
	'glove',
	'glue',
	'goldfish',
];
